name: Deploy Astro to Production

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main  # Trigger deployment when a pull request is merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker (to build and push Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub (or another registry)
      - name: Build and push Docker image
        run: |
          docker build -t docker.io/astral-gegenschein-9016/airflow:latest .
          docker push docker.io/astral-gegenschein-9016/airflow:latest

      # Deploy the Docker image to Astro
      - name: Deploy to Astro (optional, if using CLI/API for deployment)
        run: |
          curl -sSL https://astro-cli-url.com | bash
          astro auth login --token ${{ secrets.ASTRO_API_TOKEN }}
          astro deployment push --image docker.io/astral-gegenschein-9016/airflow:latest
