name: Deploy Astro to Production

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main  # Trigger deployment when a pull request is merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker (to build and push Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image to Docker registry
      - name: Build and push Docker image
        run: |
          docker build -t docker.io/astral-gegenschein-9016/airflow:latest .
          docker push docker.io/astral-gegenschein-9016/airflow:latest

      # Deploy the Docker image to Astro using Deployment API Token
      - name: Deploy to Astro
        run: |
          curl -sSL https://astro-cli-url.com | bash  # Install Astro CLI if not already installed
          echo "Deploying to Astro"
          # Authenticate with Astro using Deployment API Token
          astro auth login --token ${{ secrets.ASTRO_API_TOKEN }}
          # Push the image to Astro
          astro deployment push --image docker.io/astral-gegenschein-9016/airflow:latest
